version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  web-app:
    build: 
      context: .
      dockerfile: docker/chatbot.Dockerfile
    ports:
      - 8501:8501